language: rust
rust: nightly
cache: cargo

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-6.0
      - ubuntu-toolchain-r-test
    packages:
      - clang-6.0
      - clang-tools-6.0
      - clang-6.0-doc
      - libclang-common-6.0-dev
      - libclang-6.0-dev
      - libclang1-6.0
      - libllvm6.0
      - llvm-6.0
      - llvm-6.0-dev
      - llvm-6.0-doc
      - llvm-6.0-examples
      - llvm-6.0-runtime
      - clang-format-6.0
      - python-clang-6.0
      - lld-6.0
      - libfuzzer-6.0-dev

before_script:
    - export PATH="$PATH:$HOME/.cargo/bin"

script:
    - cargo build --examples
    - cargo doc --no-deps
    - cargo test
