language: rust
rust: nightly
cache: cargo

addons:
  apt:
    sources:
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-8 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
      - ubuntu-toolchain-r-test
    packages:
      - clang-8
      - clang-tools-8
      - clang-8-doc
      - libclang-common-8-dev
      - libclang-8-dev
      - libclang1-8
      - libllvm8
      - llvm-8
      - llvm-8-dev
      - llvm-8-doc
      - llvm-8-examples
      - llvm-8-runtime
      - clang-format-8
      - python-clang-8
      - lld-8
      - libfuzzer-8-dev

before_script:
    - wget https://github.com/jacob-hughes/llvm-readobj-bin/blob/master/archive/llvm-8-readobj-v3-stackmap-x86-64-gnu-linux.tar.gz -o /tmp/llvm-8-readobj.tar.gz
    - tar -xzvf /tmp/llvm-8-readobj-v3-stackmap-x86-64-gnu-linux.tar.gz
    - export LLVM_READOBJ_PATH="/tmp/llvm-8-readobj-v3-stackmap-x86-64-gnu-linux"
    - export PATH="$PATH:$HOME/.cargo/bin"

script:
    - cargo build --examples
    - cargo doc --no-deps
    - cargo test
