# The service providing the commit statuses to GitHub.
status = [
  "buildbot/buildbot-build-script"
]

# Allow ten mins for builds.
timeout_sec = 600

# Have bors delete auto-merged branches
delete_merged_branches = true
